### ISSUE TITLE
Compatibility Issue w/Chrome: No decimals

### ISSUE THREAD

**Issue by RDoliveros** [mitchbaum/RoofTracker-Web-App#13]
When you want to add decimals in any popup interface in certain computers using Chrome, decimals won't be accepted. You can enter comma as in European notation but then you get a NaN error.

![image](https://user-images.githubusercontent.com/75135361/223139179-7bba1b7a-71f7-41cc-9e22-965676b8b70c.png)

**Comment by mitchbaum** [comment]
@RDoliveros 
Could you check with me which version of Chrome this bug occurs in?

Top right corner of chrome -> 3 dots -> help -> click "About Google Chrome" 
![Screen Shot 2023-03-06 at 9 34 35 AM](https://user-images.githubusercontent.com/71997310/223156627-780e074c-1fa4-4bea-a804-9281fc23c009.png)

**Comment by RDoliveros** [comment]
other teammates have the same issue. I can ask them for their computer or chrome info if needed.

The decimals work on Edge. That's what I have been using to work in RT.

**Comment by mitchbaum** [comment]
@RDoliveros 
I think what's causing the issue is a conversion problem between the Latin American keyboard and the QWERTY keyboard (US version). Its most likely a problem the browser is causing when handling currency as RT is written assuming US dollar as the currency while the browser being used is set to the peso or other currency type (USA uses decimals to denote cents while other countries use the comma - like you mentioned above).

I'll need to do some research on this for a solution, but please use that Edge workaround for now.

**Comment by RDoliveros** [comment]
Sure.

I thought about it too, but my limited understanding is that changing USA keyboard to Spanish just changes the keybinding layout not the input, and shouldn't affect this issue. Also, if that was the problem edge wouldn't work either. I have changed settings to english keyboard and doesn't work.

This is a minor inconvenience, and all the team that has an issue now knows to just use Edge and not worry about it.

**Comment by mitchbaum** [comment]
@RDoliveros 

I just added a possible fix. Could you verify if it works as expected in the Chrome browsers now?

**Comment by RDoliveros** [comment]
IT WORKS!! whatever you did was exactly the issue. Awesome
